/* KoW Companion Multilingual v4.5.0 TEST4 — runtime multilingual QA. */
(function(){
'use strict';
const QA_VERSION='v450-test4-runtime';
const EXPECTED_TITLE='KoW Companion Multilingual v4.5.0 TEST';
const SAFE=new Set(['XP','ORV','SRV','MAXED','IN PROGRESS','NOT STARTED','CURRENT','NEXT']);
const dicts=()=>window.KOW_CLEAN_I18N?.getDictionaries?.()||{en:window.KOW_I18N_EN||{},fr:window.KOW_I18N_FR||{},de:window.KOW_I18N_DE||{},it:window.KOW_I18N_IT||{}};
const lang=()=>window.KOW_CLEAN_I18N?.current?.()||document.documentElement.lang||'en';
const norm=s=>String(s??'').replace(/\s+/g,' ').trim();
function missing(l){if(l==='en')return[];const d=dicts(),t=d[l]||{};return Object.keys(d.en||{}).filter(k=>!Object.prototype.hasOwnProperty.call(t,k));}
function same(l){if(l==='en')return[];const d=dicts(),t=d[l]||{};return Object.keys(d.en||{}).filter(k=>t[k]===k&&/[A-Za-z]/.test(k)&&!SAFE.has(k));}
function visible(e){if(!e||!e.isConnected)return false;const s=getComputedStyle(e);return s.display!=='none'&&s.visibility!=='hidden';}
function rendered(l){if(l==='en')return[];const d=dicts(),en=d.en||{},to=d[l]||{},keys=Object.keys(en).filter(k=>/[A-Za-z]/.test(k)&&to[k]&&to[k]!==k&&!SAFE.has(k)).sort((a,b)=>b.length-a.length),out=[],seen=new Set();const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode())){const p=n.parentElement;if(!p||!visible(p)||p.closest('#cleanLanguageQaCard')||['SCRIPT','STYLE','CODE','PRE','TEXTAREA'].includes(p.tagName))continue;const text=norm(n.nodeValue);if(!text)continue;if(Object.values(to).some(v=>norm(v)===text))continue;for(const k of keys){if(text.includes(k)){const sig=text+'|'+k;if(!seen.has(sig)){seen.add(sig);out.push({text,key:k});}break;}}}return out;}
function identity(){const a=[];if(document.title!==EXPECTED_TITLE)a.push('Wrong document title/build identity: '+document.title);const h=location.hostname,p=location.pathname;if(h!=='multilingualtest.firestorm-companion.uk'&&!(h==='rogerangliss-byte.github.io'&&p.startsWith('/KoW-Companion--Multilingual-Test')))a.push('Wrong QA deployment: '+location.href);return a;}
function qaData(choice='all'){const active=lang(),ls=choice==='all'?['en','fr','de','it']:[choice],names={en:'English',fr:'French',de:'German',it:'Italian'};return ls.map(l=>{const m=missing(l),s=same(l),skip=l!==active,r=skip?[]:rendered(l),issues=[...m.map(x=>'[missing key] '+x),...s.map(x=>'[same as English] '+x),...r.map(x=>'[rendered English] '+x.text+'  ← matched: '+x.key),...identity().map(x=>'[build identity] '+x)];return {lang:l,name:names[l],status:skip?(issues.length?'WARNING':'DICTIONARY ONLY'):(issues.length?'FAIL':'PASS'),missing:m,untranslated:s,runtime:r,runtimeSkipped:skip,issues};});}
function buildReport(choice='all'){const rows=qaData(choice),lines=['KoW Companion Multilingual v4.5.0 TEST — Runtime Language QA Report','QA module: '+QA_VERSION,'Active app language: '+lang(),'URL: '+location.href,'Document title: '+document.title,'Generated: '+new Date().toISOString(),'','IMPORTANT: rendered-browser QA is authoritative only for the currently active app language. Switch the app language in Settings and run again for each language.','','SUMMARY'];rows.forEach(r=>lines.push(`${r.name}: ${r.status} — ${r.issues.length} issues (${r.missing.length} missing, ${r.untranslated.length} same-as-English, ${r.runtime.length} rendered-English${r.runtimeSkipped?', runtime scan skipped':''})`));rows.forEach(r=>{lines.push('',`=== ${r.name.toUpperCase()} — ${r.status} ===`);if(r.runtimeSkipped)lines.push('Rendered-browser scan skipped because this is not the active app language.');if(!r.issues.length)lines.push('No translation or rendered-English issues detected for this language.');else r.issues.forEach((x,i)=>lines.push(`${i+1}. ${x}`));});return lines.join('\n');}
function resultHtml(c){return qaData(c).map(r=>`<div style="margin:12px 0"><b>${r.name} — ${r.status}</b><div>${r.runtimeSkipped?'Runtime scan skipped: switch the app to this language.<br>':''}${r.issues.length?r.issues.map(x=>'• '+x).join('<br>'):'No missing keys, same-as-English values or rendered English detected.'}</div></div>`).join('');}
function download(){const c=document.getElementById('cleanQaLanguage')?.value||lang(),b=new Blob([buildReport(c)],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`KoW-Runtime-Language-QA-v4.5.0-${c}-${new Date().toISOString().replace(/[:.]/g,'-')}.txt`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(){const settings=document.getElementById('settings');if(!settings)return;let card=document.getElementById('cleanLanguageQaCard');if(!card){card=document.createElement('div');card.id='cleanLanguageQaCard';card.className='card wide';settings.appendChild(card);}card.dataset.qaVersion=QA_VERSION;card.innerHTML=`<h2>🧪 Runtime Language QA / Translation Test</h2><p class="notice"><b>Authoritative browser QA.</b> Checks dictionary coverage, v4.5.0 TEST deployment and the currently rendered interface.</p><div class="notice"><b>QA module ${QA_VERSION}</b> · Active language: <b>${lang()}</b></div><label>Language to test</label><select id="cleanQaLanguage"><option value="en">English</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="it">Italiano</option><option value="all">All Languages</option></select><button id="cleanQaRun" class="primary" type="button">▶ Run Runtime Language QA</button><button id="cleanQaDownload" class="primary" type="button">⬇ Download Runtime QA Report</button><div id="cleanQaResult" class="notice">No runtime language test has been run yet.</div>`;card.querySelector('#cleanQaLanguage').value=lang();card.querySelector('#cleanQaRun').onclick=()=>document.getElementById('cleanQaResult').innerHTML=resultHtml(document.getElementById('cleanQaLanguage').value);card.querySelector('#cleanQaDownload').onclick=download;}
document.addEventListener('DOMContentLoaded',()=>setTimeout(render,0));window.addEventListener('load',render);if(document.readyState!=='loading')setTimeout(render,0);window.KOW_CLEAN_QA={QA_VERSION,qaData,buildReport,renderedEnglish:rendered,render};
})();
