/* v4.6.0 — dynamic multilingual rendering layer. QA remains validator only. */
(function(){
'use strict';
const PATCH={
fr:{
'saved Officers':'Officiers enregistrés','Highest progress:':'Progression la plus élevée :','Showing ':'Affichage de ','Use Current Held Resources':'Utiliser les ressources actuellement détenues','Use Current Détenu Resources':'Utiliser les ressources actuellement détenues','Shared Legendary badge resources detected:':'Ressources de Badges légendaires partagées détectées :','Remaining badge shortfall:':'Badges encore manquants :','Shared Légendaire badge resources detected:':'Ressources de Badges légendaires partagées détectées :','Remaining badge manquant:':'Badges encore manquants :','Search officers':'Rechercher des Officiers'},
de:{
'saved Officers':'gespeicherte Offiziere','Highest progress:':'Höchster Fortschritt:','Showing ':'Anzeige: ','Use Current Held Resources':'Aktuell vorhandene Ressourcen verwenden','Use Current Vorhanden Resources':'Aktuell vorhandene Ressourcen verwenden','Shared Legendary badge resources detected:':'Gemeinsame legendäre Abzeichenressourcen erkannt:','Shared Legendär badge resources detected:':'Gemeinsame legendäre Abzeichenressourcen erkannt:','Remaining badge shortfall:':'Verbleibender Abzeichenfehlbestand:','Remaining badge Fehlbestand:':'Verbleibender Abzeichenfehlbestand:','Search officers':'Offiziere suchen'},
it:{
'saved Officers':'Ufficiali salvati','Highest progress:':'Progresso più alto:','Showing ':'Visualizzati: ','Use Current Held Resources':'Usa le risorse attualmente possedute','Use Current Posseduto Resources':'Usa le risorse attualmente possedute','Shared Legendary badge resources detected:':'Rilevate risorse Badge Leggendari condivise:','Shared Leggendario badge resources detected:':'Rilevate risorse Badge Leggendari condivise:','Remaining badge shortfall:':'Badge mancanti rimanenti:','Remaining badge mancante:':'Badge mancanti rimanenti:','Search officers':'Cerca Ufficiali'}
};
function active(){return window.KOW_CLEAN_I18N?.current?.()||document.getElementById('appLanguage')?.value||'en'}
function extendDictionaries(){Object.assign(window.KOW_I18N_FR||{},PATCH.fr);Object.assign(window.KOW_I18N_DE||{},PATCH.de);Object.assign(window.KOW_I18N_IT||{},PATCH.it)}
function replaceText(s,map){let out=String(s||'');for(const [a,b] of Object.entries(map).sort((x,y)=>y[0].length-x[0].length)){if(out.includes(a))out=out.split(a).join(b)}return out}
function translateDynamic(root=document.body){const l=active(),map=PATCH[l];if(!map||l==='en'||!root)return;const roots=root===document.body?['progress','planner','database','releases','inventory','development'].map(id=>document.getElementById(id)).filter(Boolean):[root];for(const r of roots){const w=document.createTreeWalker(r,NodeFilter.SHOW_TEXT);while(w.nextNode()){const n=w.currentNode;if(!n.parentElement||n.parentElement.closest('script,style,code,pre,#v460QaCard,[data-no-translate]'))continue;const x=n.nodeValue,y=replaceText(x,map);if(y!==x)n.nodeValue=y}r.querySelectorAll?.('[placeholder],[title],[aria-label]').forEach(el=>{for(const a of ['placeholder','title','aria-label']){const x=el.getAttribute(a);if(!x)continue;const y=replaceText(x,map);if(y!==x)el.setAttribute(a,y)}})}}
function install(){extendDictionaries();translateDynamic();window.KOW_CLEAN_I18N?.forceApply?.();setTimeout(translateDynamic,100);setTimeout(translateDynamic,400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();window.addEventListener('load',install);
new MutationObserver(ms=>{for(const m of ms){if(m.type==='characterData'){translateDynamic(m.target.parentElement);continue}for(const n of m.addedNodes||[]){if(n.nodeType===1)translateDynamic(n);else if(n.nodeType===3&&n.parentElement)translateDynamic(n.parentElement)}}}).observe(document.documentElement,{subtree:true,childList:true,characterData:true});
window.KOW_DYNAMIC_I18N={apply:translateDynamic,patches:PATCH};
})();
