(function(){'use strict';
const $=id=>document.getElementById(id),K='kow-language-v460';
const views=['dashboard','progress','officer','stars','development','xp','planner','database','help','releases','inventory','settings'];
const features=['officerReadinessCard','officerReadinessGrid','inventoryIntelligenceCard','smartDashboardCard','v460UpgradeTargetsCard','futureOfficerForecastCard','releaseCalendar','multiPlannerCard','quickProgressModal'];
const controls=['saveInventory','openUserGuide','officerSelect','starLevel','officerLevel','trainingLevel'];
const guideParity={h2:1,h3:13,h4:9,listItems:24,paragraphs:37};
const guideRequired={fr:['1. Inventaire','2. Officier','3. Étoiles','4. Développement','5. XP','6. Planificateur','7. Planificateur','8. Sauvegarder','9. Base de données','10. Calendrier','11. Paramètres'],de:['1. Inventar','2. Offizier','3. Sterne','4. Entwicklung','5. XP','6. Planer','7. Mehr-Offizier','8. Fortschritt','9. Datenbank','10. Wiederkehrender','11. Einstellungen'],it:['1. Inventario','2. Ufficiale','3. Stelle','4. Sviluppo','5. XP','6. Pianificatore','7. Pianificatore','8. Salva','9. Banca dati','10. Calendario','11. Impostazioni']};
const englishBleed=['Officer Readiness Intelligence','Upgrade Targets & Recommendations','Calculate Target Recommendation','Forecast future Officer costs','Current month:','Next scheduled release:','Open Inventory','Open Officer Progress','Save Inventory','Central Inventory','Officer Development','Backup & Restore','User Guide','A normal browser refresh','Selected Officer and current app','Shared Inventory','Create a priority list','The Inventory now follows','The forecast now uses','Start here. Enter','Use Search','The selected Officer','Enter current and target','Plans are preview-only','The Releases tab shows','Settings contains'];
const labels={en:['Full App QA / Functionality Parity','Run ENTIRE APP QA','PASS','FAIL'],fr:['QA complète / Parité fonctionnelle','Lancer le QA de TOUTE L’APP','RÉUSSI','ÉCHEC'],de:['Vollständige App-QA / Funktionsparität','GESAMTE APP prüfen','BESTANDEN','FEHLER'],it:['QA completa / Parità funzionale','Esegui QA INTERA APP','SUPERATO','NON SUPERATO']};
function lang(){return localStorage.getItem(K)||'en'}
function run(){const x=lang(),q=labels[x]||labels.en,o=$('mlQaResults');
 const missingViews=views.filter(id=>!$(id)); const missingFeatures=features.filter(id=>!$(id)); const missingControls=controls.filter(id=>!$(id));
 const guide=$('help'); const fullGuide=guide?.querySelector('.multilingual-full-guide')||guide; const guideText=fullGuide?.innerText||''; const guideH2=fullGuide?fullGuide.querySelectorAll('h2').length:0; const guideH3=fullGuide?fullGuide.querySelectorAll('h3').length:0; const guideH4=fullGuide?fullGuide.querySelectorAll('h4').length:0; const guideListItems=fullGuide?fullGuide.querySelectorAll('li').length:0; const guideParagraphs=fullGuide?fullGuide.querySelectorAll('p').length:0;
 const missingGuideConcepts=x==='en'?[]:(guideRequired[x]||[]).filter(s=>!guideText.includes(s));
 const guideOk=x==='en'||(guideH2===guideParity.h2&&guideH3===guideParity.h3&&guideH4===guideParity.h4&&guideListItems===guideParity.listItems&&guideParagraphs===guideParity.paragraphs&&!missingGuideConcepts.length&&!guideText.includes('**'));
 const guideParityDetail=[`h2 ${guideH2}/${guideParity.h2}`,`h3 ${guideH3}/${guideParity.h3}`,`h4 ${guideH4}/${guideParity.h4}`,`list items ${guideListItems}/${guideParity.listItems}`,`paragraphs ${guideParagraphs}/${guideParity.paragraphs}`].concat(missingGuideConcepts.map(s=>'missing: '+s));
 const body=document.body.innerText||''; const bleed=x==='en'?[]:englishBleed.filter(s=>body.includes(s));
 const banner=!!$('multilingualTestBanner')&&($('multilingualTestBanner').innerText||'').includes('NOT LIVE');
 const officerRows=document.querySelectorAll('.inv-officer-badge-row').length; const portraitsExpected=officerRows>=60;
 const navCount=document.querySelectorAll('.bottom-nav button, nav button').length; const navigationOk=navCount>=12;
 const tests=[['All 12 app sections',!missingViews.length,missingViews],['v4.6.0 feature parity',!missingFeatures.length,missingFeatures],['Critical controls',!missingControls.length,missingControls],['1:1 User Guide content parity',guideOk,guideParityDetail],['Rendered English bleed',!bleed.length,bleed],['TEST safety banner',banner,[]],['Officer/Inventory dataset',portraitsExpected,[`${officerRows} Officer rows`]],['12-tab navigation',navigationOk,[`${navCount} navigation buttons`]]];
 const ok=tests.every(t=>t[1]); o.innerHTML='<div class="notice"><b>'+(ok?q[2]:q[3])+' — ENTIRE APP QA</b></div>'+tests.map(t=>'<div><b>'+(t[1]?'✅ ':'❌ ')+t[0]+':</b> '+(t[1]?q[2]:(t[2].join(' · ')||q[3]))+'</div>').join('')+'<div class="notice"><b>Scope:</b> Dashboard, Progress, Officer, Stars, Development, XP, Planner, Database, Help, Releases, Inventory, Settings; v4.6.0 feature cards; critical controls; translated full guide; visible English bleed; TEST banner; Officer dataset; navigation. Functional actions still require the manual QA checklist after this automated structural/render test.</div>';
}
function init(){let s=$('settings');if(!s||$('mlQaCard'))return;let q=labels[lang()]||labels.en,c=document.createElement('article');c.id='mlQaCard';c.className='card wide';c.innerHTML='<h2>🧪 '+q[0]+'</h2><p class="notice">QA3 audits the ENTIRE rendered app plus English Live v4.6.0 feature parity and 1:1 translated User Guide content parity. PASS is blocked by missing app sections, core v4.6.0 features, critical controls, guide coverage, visible English bleed or missing TEST safeguards.</p><button id="mlQaRun" class="app-action-primary">'+q[1]+'</button><div id="mlQaResults"></div>';s.appendChild(c);$('mlQaRun').onclick=run}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,700));else setTimeout(init,500)})();