(function(){'use strict';
const $=id=>document.getElementById(id),K='kow-language-v460';
const views=['dashboard','progress','officer','stars','development','xp','planner','database','help','releases','inventory','settings'];
const features=['officerReadinessCard','officerReadinessGrid','inventoryIntelligenceCard','smartDashboardCard','v460UpgradeTargetsCard','futureOfficerForecastCard','releaseCalendar','multiPlannerCard','quickProgressModal'];
const controls=['saveInventory','openUserGuide','officerSelect','starLevel','officerLevel','trainingLevel'];
const guideParity={headings:28,listItems:40,paragraphs:31};
const guideRequired={
 fr:['Objectifs d’amélioration et recommandations','Données dynamiques des Officiers','Référence dynamique de prévision','Inventaire central','Règles des coffres Légendaires','Officiers Légendaires originaux','Progression d’Officier','Besoins confirmés en Badges','Optimiseur de ressources','Planificateur d’amélioration multi-Officiers','Planification avancée et futurs Officiers','Tableau de bord de préparation','Persistance de l’état de travail','Calendrier récurrent des sorties','Base de données des Officiers','Sauvegarde et restauration','Principe important de planification'],
 de:['Upgrade-Ziele & Empfehlungen','Dynamische Offiziersdaten','Dynamische Prognosebasis','Zentrales Inventar','Regeln für legendäre Truhen','Ursprüngliche legendäre Offiziere','Offiziersfortschritt','Bestätigte Abzeichenanforderungen','Ressourcen-Optimierer','Mehr-Offizier-Upgrade-Planer','Erweiterte Planung und zukünftige Offiziere','Planungsbereitschafts-Dashboard','Arbeitszustands-Persistenz','Wiederkehrender Veröffentlichungszyklus','Offiziersdatenbank','Backup & Wiederherstellung','Wichtiges Planungsprinzip'],
 it:['Obiettivi di potenziamento e consigli','Dati dinamici degli Ufficiali','Base dinamica della previsione','Inventario centrale','Regole delle Casse Leggendarie','Ufficiali Leggendari Originali','Progresso Ufficiale','Requisiti Badge confermati','Ottimizzatore risorse','Pianificatore potenziamento multi-Ufficiale','Pianificazione avanzata e futuri Ufficiali','Dashboard preparazione','Persistenza dello stato di lavoro','Calendario ricorrente delle uscite','Banca dati Ufficiali','Backup e ripristino','Principio importante di pianificazione']
};
const englishBleed=['Officer Readiness Intelligence','Upgrade Targets & Recommendations','Calculate Target Recommendation','Forecast future Officer costs','Current month:','Next scheduled release:','Open Inventory','Open Officer Progress','Save Inventory','Central Inventory','Officer Development','Backup & Restore','User Guide'];
const labels={en:['Full App QA / Functionality Parity','Run ENTIRE APP QA','PASS','FAIL'],fr:['QA complète / Parité fonctionnelle','Lancer le QA de TOUTE L’APP','RÉUSSI','ÉCHEC'],de:['Vollständige App-QA / Funktionsparität','GESAMTE APP prüfen','BESTANDEN','FEHLER'],it:['QA completa / Parità funzionale','Esegui QA INTERA APP','SUPERATO','NON SUPERATO']};
function lang(){return localStorage.getItem(K)||'en'}
function run(){const x=lang(),q=labels[x]||labels.en,o=$('mlQaResults');
 const missingViews=views.filter(id=>!$(id)); const missingFeatures=features.filter(id=>!$(id)); const missingControls=controls.filter(id=>!$(id));
 const guide=$('help'); const fullGuide=guide?.querySelector('.multilingual-full-guide')||guide; const guideText=fullGuide?.innerText||''; const guideHeadings=fullGuide?fullGuide.querySelectorAll('h2,h3').length:0; const guideListItems=fullGuide?fullGuide.querySelectorAll('li').length:0; const guideParagraphs=fullGuide?fullGuide.querySelectorAll('p').length:0;
 const missingGuideConcepts=x==='en'?[]:(guideRequired[x]||[]).filter(s=>!guideText.includes(s));
 const guideOk=x==='en'||(guideHeadings===guideParity.headings&&guideListItems===guideParity.listItems&&guideParagraphs===guideParity.paragraphs&&!missingGuideConcepts.length&&!guideText.includes('**'));
 const guideParityDetail=[`headings ${guideHeadings}/${guideParity.headings}`,`list items ${guideListItems}/${guideParity.listItems}`,`paragraphs ${guideParagraphs}/${guideParity.paragraphs}`].concat(missingGuideConcepts.map(s=>'missing: '+s));
 const body=document.body.innerText||''; const bleed=x==='en'?[]:englishBleed.filter(s=>body.includes(s));
 const banner=!!$('multilingualTestBanner')&&($('multilingualTestBanner').innerText||'').includes('NOT LIVE');
 const officerRows=document.querySelectorAll('.inv-officer-badge-row').length; const portraitsExpected=officerRows>=60;
 const navCount=document.querySelectorAll('.bottom-nav button, nav button').length; const navigationOk=navCount>=12;
 const tests=[['All 12 app sections',!missingViews.length,missingViews],['v4.6.0 feature parity',!missingFeatures.length,missingFeatures],['Critical controls',!missingControls.length,missingControls],['1:1 User Guide content parity',guideOk,guideParityDetail],['Rendered English bleed',!bleed.length,bleed],['TEST safety banner',banner,[]],['Officer/Inventory dataset',portraitsExpected,[`${officerRows} Officer rows`]],['12-tab navigation',navigationOk,[`${navCount} navigation buttons`]]];
 const ok=tests.every(t=>t[1]); o.innerHTML='<div class="notice"><b>'+(ok?q[2]:q[3])+' — ENTIRE APP QA</b></div>'+tests.map(t=>'<div><b>'+(t[1]?'✅ ':'❌ ')+t[0]+':</b> '+(t[1]?q[2]:(t[2].join(' · ')||q[3]))+'</div>').join('')+'<div class="notice"><b>Scope:</b> Dashboard, Progress, Officer, Stars, Development, XP, Planner, Database, Help, Releases, Inventory, Settings; v4.6.0 feature cards; critical controls; translated full guide; visible English bleed; TEST banner; Officer dataset; navigation. Functional actions still require the manual QA checklist after this automated structural/render test.</div>';
}
function init(){let s=$('settings');if(!s||$('mlQaCard'))return;let q=labels[lang()]||labels.en,c=document.createElement('article');c.id='mlQaCard';c.className='card wide';c.innerHTML='<h2>🧪 '+q[0]+'</h2><p class="notice">QA3 audits the ENTIRE rendered app plus English Live v4.6.0 feature parity and 1:1 translated User Guide content parity. PASS is blocked by missing app sections, core v4.6.0 features, critical controls, guide coverage, visible English bleed or missing TEST safeguards.</p><button id="mlQaRun" class="app-action-primary">'+q[1]+'</button><div id="mlQaResults"></div>';s.appendChild(c);$('mlQaRun').onclick=run}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,700));else setTimeout(init,500)})();